bitwiseapp/accounts/urls.py
from django.urls import path

from .views import ProfileCreateView, ProfileUpdateView


urlpatterns = [
    path("<int:pk>", ProfileUpdateView.as_view(), name="profile_update"),
    path("create", ProfileCreateView.as_view(), name="profile_create"),
]

app_name = "accounts"

bitwiseapp/bitwise/urls.py
from django.urls import path

from .views import HomepageView

urlpatterns = [
    path("", HomepageView, name="index"),
]

app_name = "bitwise"

bitwiseapp/bitwiseapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bitwise.urls", namespace="default")),
    path("home/", include("bitwise.urls", namespace="bitwise")),
    path("profile/", include("accounts.urls", namespace="profile")),
    path("modules/", include("modules.urls", namespace="modules")),
    path("registration/", include("django.contrib.auth.urls")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitwiseapp/modules/urls.py
from django.urls import path

from .views import (
    CategoryListView,
    CommentDeleteView,
    PythonCompile,
    PythonCompiler,
    WebCompiler, 
    Execute,
    CodeRedirect, 
    GalleryDeleteView,
    ModuleCreateView,
    SearchResultsView,
    ModuleDeleteView,
    ModuleDetailView,
    ModuleUpdateView,
)

urlpatterns = [
    path("list/", CategoryListView.as_view(), name="ModuleCategory"),
    path("lesson/<int:pk>", ModuleDetailView, name="Module"),
    path("lesson/add", ModuleCreateView, name="ModuleCreate"),
    path("search/", SearchResultsView, name="ModuleSearch"),
    path("lesson/<int:pk>/edit", ModuleUpdateView.as_view(), name="ModuleUpdate"),
    path("lesson/<int:pk>/delete", ModuleDeleteView, name="ModuleDelete"),
    path("lesson/<int:pk>/comment/delete", CommentDeleteView, name="CommentDelete"),
    path("lesson/<int:pk>/gallery/delete", GalleryDeleteView, name="GalleryDelete"),
    path("code/python", PythonCompiler, name="PythonCompiler"),
    path("code/webdev", WebCompiler, name="WebCompiler"),
    path("code/python/run", PythonCompile, name="RunCode"),
    path("code/", CodeRedirect, name="Code"), 
]

app_name = "modules"

bitwiseapp/quizzes/urls.py
from django.urls import path

from .views import (
    QuizListView,
    QuizAnswerView,
    QuizInfoDetailView,
    quiz_detail_data_view,
    save_quiz_view,
    create_quiz,
    quiz_detail,
    quiz_update,
    answer_delete,
    question_delete
)

urlpatterns = [
    path('', QuizListView.as_view(), name='quiz_list_view'),
    path('quiz/<pk>/info', QuizInfoDetailView.as_view(), name='quiz_view'),
    path('quiz/<pk>', QuizAnswerView.as_view(), name="quiz_answer"), # for answering the quiz
    path('quiz/<pk>/data', quiz_detail_data_view, name='quiz_data_view'), # for checking data before implementation for quiz
    path('quiz/<pk>/save', save_quiz_view, name='quiz_save_view'),
    path('create', create_quiz, name="create_quiz_view"),
    path('quiz/<quiz_id>/update', quiz_update, name='quiz_update'),
    path('quiz/<answer_id>/answer_delete', answer_delete, name='answer_delete'),
    path('quiz/<question_id>/question_delete', question_delete, name='question_delete')
]

app_name = 'quizzes'

bitwiseapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bitwise{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
    <div id="content container-fluid overflow-hidden">
        <div class="row w-100">
            <div class="sidebar col-12 col-sm-2 col-xl-1 px-0 bg-secondary d-flex sticky-top justify-content-center" style="padding-left: .5rem !important;">
                <div class="d-flex flex-sm-column flex-row flex-nowrap bg-secondary align-items-center sticky-top">
                    <ul class="nav nav-pills nav-flush flex-sm-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link {% if '/profile' in request.path %}active{% endif %}" aria-current="page" href="{% url 'profile:profile_update' request.user.profile.pk %}" id="index"><i class="bi bi-person-circle fs-1"></i></a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link {% if '/home' in request.path or request.path == '/' %}active{% endif %}" aria-current="page" href="{% url 'bitwise:index' %}" id="index"><i class="bi bi-house fs-1"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/modules/list/' in request.path or '/modules/search' in request.path or '/modules/lesson' in request.path %}active{% endif %}" href="{% url 'modules:ModuleCategory' %}" id="module"><i class="bi bi-file-earmark-richtext fs-1"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/quizzes' in request.path %}active{% endif %}" href="{% url  'quizzes:quiz_list_view' %}" id="code"><i class="bi bi-file-binary fs-1"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if '/modules/code/' in request.path %}active{% endif %}" href="{% url  'modules:Code' %}" id="code"><i class="bi bi-pc-display-horizontal fs-1"></i></a>
                        </li>
                    </ul> 
                </div>
            </div>
            <div class="col p-3 min-vh-100">
                {% block main %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% block scripts %}{% endblock %}
    <!-- <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- <script>
        $(document).ready(function () {
            var url = window.location;
            $('ul.nav a').filter(function() {
                return this.href != url;
            }).removeClass('active');

            $('ul.nav a').filter(function() {
                return this.href == url;
            }).addClass('active');
        });
    </script> -->
</body>
</html>

bitwiseapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bitwise{% endblock %}
{% block main %}
    {% if request.user.is_authenticated %}
        <h1>Welcome to Bitwise, {{ request.user.profile.display_name }}!</h1>
        <form action="{% url 'logout'%}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary">LOG OUT</button>
        </form>
    {% else %}
        <h1>Welcome to Bitwise! Would you like to <a href="{% url 'login' %}">log-in</a>?</h1>
    {% endif %}

    <hr>
    <ul class="nav nav-pills mt-2" id="myTab" role="tablist">
        <li class="nav-item " role="presentation">
            <button class="nav-link n-btn active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Modules</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Quizzes</button>
        </li>
    </ul>
    <div class="tab-content container text-center" id="myTabContent">
        <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
            <div class="row">
                {% for module in modules.all %}
                    <div class="col-md-4"> 
                        <div class="card my-4 mx-auto">
                            <div class="row g-0">
                                {% if module.category.name == "C++" %}
                                    <img src="{% static 'img/card_cplusplus.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                                {% elif module.category.name == "Web Development" %}
                                    <img src="{% static 'img/card_webdev.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                                {% elif module.category.name == "Python" %}
                                    <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                                {% else %}
                                    <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                                {% endif %}
                                <div class="d-flex" style="background-color: #D9D9D9;">
                                    <div class="card-body align-self-center mx-4">
                                        <h2 class="card-title"><a href="{{ module.get_absolute_url }}">{{ module.title }}</a></h2>
                                        <p class="card-subtitle mb-2 text-muted">By {{ module.author }}</p>
                                        <h5>Category: {{ module.category.name }}</h5>
                                        <!-- <div class="card-body">
                                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe explicabo a suscipit impedit maiores dolorum similique nesciunt mollitia, omnis quaerat sed delectus quos aut id repudiandae magnam error! Odio nisi natus repellat nulla a fugiat aperiam quam dolores necessitatibus distinctio quaerat labore aut, qui odit eum eveniet nihil quis quasi.</p>
                                        </div>  -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                {% endfor %}
            </div>
        </div>
        <div class="tab-pane fade" id="profile-tab-pane" role="tabpanel" aria-labelledby="profile-tab" tabindex="0">
            <div class="row">
                {% for quiz in quizzes.all %}
                    <div class="col-md-4"> 
                        <div class="card my-4 mx-auto">
                            <div class="row g-0">
                                <div class="d-flex" style="background-color: #D9D9D9;">
                                    <div class="card-body align-self-center mx-4">
                                        <h2 class="card-title"><a href="{{ quiz.get_absolute_url }}">{{ quiz.name }}</a></h2>
                                        <p class="card-subtitle mb-2 text-muted">By {{ quiz.created_by }}</p>
                                        <h5>Category: {{ quiz.topic.name }}</h5>
                                        <h5>Difficulty: {{ quiz.difficulty }}</h5>
                                        <!-- <div class="card-body">
                                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe explicabo a suscipit impedit maiores dolorum similique nesciunt mollitia, omnis quaerat sed delectus quos aut id repudiandae magnam error! Odio nisi natus repellat nulla a fugiat aperiam quam dolores necessitatibus distinctio quaerat labore aut, qui odit eum eveniet nihil quis quasi.</p>
                                        </div>  -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>    
                {% endfor %}
            </div>
        </div>
        </div>
    </div>
{% endblock %}

bitwiseapp/templates/profile_create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Bitwise | Create Profile{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    
</head>
<body>
  <div class="container my-2">
    <h1>Profile Creation</h1>
    <hr />
    <div class="container bg-light border rounded text-center" style = "max-width: 600px;">
      <form method="POST" class="my-4 mx-2">
        {% csrf_token %} {{ form }}
        <input type="submit" value="Create Profile" class="mt-4 btn btn-secondary" />
      </form>
    </div>
    <a href="{% url 'bitwise:index' %}" class="btn btn-secondary a-log">Go to homepage</a>
  </div>
</body>
</html>

bitwiseapp/templates/profile_update.html
{% extends "base.html" %}

{% block title %}
Bitwise | Update Profile
{% endblock title %}

{% block main %}
<h1>Profile Information</h1>
<hr />
<p> </p>
<!-- <form method="POST">
  {% csrf_token %} {{ form.as_p }}
  <input type="submit" value="Update" />
</form> -->
<div class="container text-center my-3 bg-light border rounded" style="max-width: 700px;">
  <div class="row my-3">
    <div class="col-4 text-end"><h3>Username:</h3></div>
    <div class="col-8 d-flex justify-content-center"><h3>{{ request.user.username }}</h3></div>
  </div>
  <form method="POST" class="lead my-3">
    {% csrf_token %}
    {% for field in form %}
        <div class="row my-3">
            <div class="col-4 text-end">
                {{ field.errors }}
                <h3>{{ field.label_tag }}</h3>
            </div>
            <div class="col-8 d-flex justify-content-center">
                {{ field }}
            </div>
        </div>
    {% endfor %}
    <button type="submit" class="mt-2 btn btn-secondary" value="Update">Update</button>
  </form>
</div>
<footer class="login-alters">
  <a href="{% url 'bitwise:index' %}" class="btn btn-secondary a-log">Go to homepage</a>
</footer>

{% endblock main %}