bitwiseapp/bitwise/urls.py
from django.urls import path

from .views import HomepageView

urlpatterns = [
    path("", HomepageView, name="index"),
]

app_name = "bitwise"

bitwiseapp/bitwiseapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bitwise.urls", namespace="default")),
    path("home/", include("bitwise.urls", namespace="bitwise")),
    path("profile/", include("accounts.urls", namespace="profile")),
    path("modules/", include("modules.urls", namespace="modules")),
    path("registration/", include("django.contrib.auth.urls")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitwiseapp/modules/urls.py
from django.urls import path

from .views import (
    CategoryListView,
    CommentDeleteView,
    PythonCompile,
    PythonCompiler,
    WebCompiler, 
    Execute,
    CodeRedirect, 
    GalleryDeleteView,
    ModuleCreateView,
    SearchResultsView,
    ModuleDeleteView,
    ModuleDetailView,
    ModuleUpdateView,
)

urlpatterns = [
    path("list/", CategoryListView.as_view(), name="ModuleCategory"),
    path("lesson/<int:pk>", ModuleDetailView, name="Module"),
    path("lesson/add", ModuleCreateView, name="ModuleCreate"),
    path("search/", SearchResultsView, name="ModuleSearch"),
    path("lesson/<int:pk>/edit", ModuleUpdateView.as_view(), name="ModuleUpdate"),
    path("lesson/<int:pk>/delete", ModuleDeleteView, name="ModuleDelete"),
    path("lesson/<int:pk>/comment/delete", CommentDeleteView, name="CommentDelete"),
    path("lesson/<int:pk>/gallery/delete", GalleryDeleteView, name="GalleryDelete"),
    path("code/python", PythonCompiler, name="PythonCompiler"),
    path("code/webdev", WebCompiler, name="WebCompiler"),
    path("code/python/run", PythonCompile, name="RunCode"),
    path("code/", CodeRedirect, name="Code"), 
]

app_name = "modules"

bitwiseapp/modules/models.py
from django.db import models
from django.urls import reverse

from accounts.models import Profile


class ModuleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Module(models.Model):
    title = models.CharField(max_length=255)
    entry = models.TextField()
    author = models.ForeignKey(
        Profile, null=True,
        default=None,
        on_delete=models.SET_NULL,
        related_name="module",
    )
    createdOn = models.DateTimeField(auto_now_add=True, null=True)
    updatedOn = models.DateTimeField(auto_now=True, null=True)
    category = models.ForeignKey(
        "ModuleCategory", on_delete=models.SET_NULL, related_name="modules", null=True
    )

    def __str__(self):
        return "{} from {}".format(self.title, self.category)
    
    def get_absolute_url(self):
        return reverse("modules:Module", args=[self.pk])
    
    class Meta:
        unique_together = [
            ["title", "createdOn"],
            ["title", "entry"]
        ]
        verbose_name = "Module"
        verbose_name_plural = "Modules"

class Comment(models.Model):
    author = models.ForeignKey(
        Profile, null=True,
        default=None,
        on_delete=models.SET_NULL,
        related_name="authoredComment"
    )
    module = models.ForeignKey(
        Module, on_delete=models.CASCADE,
        related_name="comment"
    )
    entry = models.TextField()
    createdOn = models.DateTimeField(auto_now_add=True, null=True)
    updatedOn = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return "comment by {} on {}".format(self.author, self.createdOn)
    
    class Meta:
        ordering = ["-createdOn"]
        unique_together = ["entry", "createdOn"]
        verbose_name = "Comment"
        verbose_name_plural = "Comments"


class Gallery(models.Model):
    image = models.ImageField(upload_to="images/", null=True)
    createdOn = models.DateTimeField(auto_now_add=True, null=True)
    module = models.ForeignKey(
        Module,
        on_delete=models.CASCADE,
        related_name="image"
    )

    def delete(self, *args, **kwargs):
        self.image.delete()
        super(Gallery, self).delete(*args, **kwargs)
    
    class Meta:
        ordering = ["-createdOn"]
        unique_together = ["image", "createdOn"]
        verbose_name = "Image"
        verbose_name_plural = "Images"

bitwiseapp/modules/forms.py
from django import forms

from .models import Comment, Gallery, Module


class ModuleForm(forms.ModelForm):
    class Meta:
        model = Module
        fields = [
            "title",
            "entry",
            "category",
        ]

    template_name = "module_create_snippet.html"


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "entry",
        ]


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = [
            "image", 
        ]

bitwiseapp/modules/views.py
import traceback
from contextlib import redirect_stdout
from io import StringIO

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic.edit import UpdateView
from django.views.generic.list import ListView

from django.db.models import Q
from accounts.models import Profile

from .forms import CommentForm, GalleryForm, ModuleForm
from .models import Comment, Gallery, Module, ModuleCategory


class CategoryListView(ListView):
    model = ModuleCategory
    template_name = "modules/modules_list.html"


@login_required
def ModuleDeleteView(request, pk):
    module = Module.objects.get(pk=pk)
    module.delete()
    return redirect("modules:ModuleCategory")


def ModuleDetailView(request, pk):
    module = Module.objects.get(pk=pk)
    comment_form = CommentForm()
    gallery_form = GalleryForm()

    if request.method == "POST":
        comment_form = CommentForm(request.POST, request.FILES)
        gallery_form = GalleryForm(request.POST, request.FILES)
        if comment_form.is_valid():
            comment = Comment()
            comment.author = Profile.objects.get(user=request.user)
            comment.entry = comment_form.cleaned_data.get("entry")
            comment.module = Module.objects.get(pk=pk)
            comment.save()
            return redirect("modules:Module", pk=pk)

        if gallery_form.is_valid():
            gallery = Gallery()
            gallery.image = gallery_form.cleaned_data.get("image")
            gallery.module = Module.objects.get(pk=pk)
            gallery.save()
            return redirect("modules:Module", pk=pk)

    ctx = {
        "object": module,
        "comment_form": comment_form,
        "gallery_form": gallery_form,
        "allModules": Module.objects.all(),
        "images": Gallery.objects.all(),
        "comments": Comment.objects.all(),
    }

    return render(request, "modules/modules_module.html", ctx)


@login_required
def CommentDeleteView(request, pk):
    comment = Comment.objects.get(pk=pk)
    comment.delete()
    return redirect("modules:ModuleCategory")


@login_required
def GalleryDeleteView(request, pk):
    gallery = Gallery.objects.get(pk=pk)
    gallery.delete()
    return redirect("modules:ModuleCategory")


@login_required
def ModuleCreateView(request):
    form = ModuleForm()

    if request.method == "POST":
        form = ModuleForm(request.POST, request.FILES)
        if form.is_valid():
            module = Module()
            module.title = form.cleaned_data.get("title")
            module.category = form.cleaned_data.get("category")
            module.author = Profile.objects.get(user=request.user)
            module.entry = form.cleaned_data.get("entry")
            module.save()
            return redirect("modules:Module", pk=module.pk)

    ctx = {"form": form}
    return render(request, "modules/modules_modCreate.html", ctx)


class ModuleUpdateView(UpdateView):
    model = Module
    fields = [
        "title",
        "category",
        "entry",
    ]
    template_name = "modules/modules_modUpdate.html"

    def get_success_url(self):
        return reverse_lazy("modules:Module", kwargs={"pk": self.object.pk})

def SearchResultsView(request):
    if request.method == "POST":
        searching = request.POST['searching']
        searched = Module.objects.filter(
            Q(title__contains=searching) | Q(category__name__contains=searching)
        )

    ctx = {
        "searching": searching,
        "searched": searched,
    }
    
    return render(request, 'modules/modules_search.html', ctx)

# COMPILER STUFF BELOW THIS POINT


def Execute(code):
    try:
        # Capture standard output in a buffer
        output_buffer = StringIO()
        with redirect_stdout(output_buffer):
            exec(code)
        output = output_buffer.getvalue()
    except Exception as e:
        # Provide detailed error information
        output = f"Error: {str(e)}\n{traceback.format_exc()}"
    return output


def PythonCompiler(request):
    return render(request, "modules/modules_python.html")


def WebCompiler(request): 
    return render(request, "modules/modules_web.html")


def CodeRedirect(request): 
    return render(request, "modules/modules_code.html")


def PythonCompile(request):
    if request.method == "POST":
        codeareadata = request.POST["codearea"]
        output = Execute(codeareadata)
        return render(
            request,
            "modules/modules_python.html",
            {"code": codeareadata, "output": output},
        )
    return HttpResponse("Method not allowed", status=405)

bitwiseapp/templates/modules/modules_code.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bitwise | Code Editors{% endblock %}
{% block main %}
<h1>Code Editors</h1>
<hr>
<div class="card my-4 mx-auto" style="max-width: 1200px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="python" style="width: 100%; max-height: 300px;">
        </div>
        <div class="col-md-8 d-flex" style="background-color: #D9D9D9;">
            <div class="card-body align-self-center mx-4">
                <h2 class="card-title"><a href="python">Python Code Editor</a></h2>
            </div>
        </div>
    </div>
</div>
<div class="card my-4 mx-auto" style="max-width: 1200px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="{% static 'img/card_webdev.png' %}" class="img-fluid rounded-start" alt="webdev" style="width: 100%; max-height: 300px;">
        </div>
        <div class="col-md-8 d-flex" style="background-color: #D9D9D9;">
            <div class="card-body align-self-center mx-4">
                <h2 class="card-title"><a href="webdev">Web Code Editor</a></h2>
            </div>
        </div>
    </div>
</div>

{% endblock %}

bitwiseapp/templates/modules/modules_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bitwise | Module List{% endblock %}
{% block main %}
    <h1>Modules</h1>
    <!-- <div class="form-group mt-4">
        <input type="search" class="form-control" id="search" placeholder="Search for a module..." style="max-width: 400px;">
        <button type="submit" class="mt-2 btn btn-secondary">Search</button>
    </div>  -->
    <hr>
    {% if request.user.is_authenticated %}
        {% if request.user.profile.authorized %}
            <a class="btn btn-secondary mt-4 text-end" href="{% url 'modules:ModuleCreate' %}">Create a module</a>
        {% endif %}
    {% endif %}

    <div>
        <form class="d-flex" action="{% url 'modules:ModuleSearch' %}" method="POST">
            {% csrf_token %}
            <input class="form-control me-2" name="searching" type="search" placeholder="Search...">
            <button class="btn btn-outline-secondary" type="submit">Search</button>
        </form>
    </div>

    {% for category in object_list %}
        
        {% for lesson in category.modules.all %}
            <div class="card my-4 mx-auto" style="max-width: 1200px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        {% if category.name == "C++" %}
                            <img src="{% static 'img/card_cplusplus.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                        {% elif category.name == "Web Development" %}
                            <img src="{% static 'img/card_webdev.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                        {% elif category.name == "Python" %}
                            <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                        {% else %}
                            <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                        {% endif %}
                    </div>
                    <div class="col-md-8 d-flex" style="background-color: #D9D9D9;">
                        <div class="card-body align-self-center mx-4">
                            <h2 class="card-title"><a href="{{ lesson.get_absolute_url }}">{{ lesson.title }}</a></h2>
                            <p class="card-subtitle mb-2 text-muted">By {{ lesson.author }}</p>
                            <h5>Category: {{ category.name }}</h5>
                            <!-- <div class="card-body">
                                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe explicabo a suscipit impedit maiores dolorum similique nesciunt mollitia, omnis quaerat sed delectus quos aut id repudiandae magnam error! Odio nisi natus repellat nulla a fugiat aperiam quam dolores necessitatibus distinctio quaerat labore aut, qui odit eum eveniet nihil quis quasi.</p>
                            </div>  -->
                        </div>
                    </div>
                </div>
            </div>  
        {% endfor %}
    {% endfor %}
{% endblock  %}

bitwiseapp/templates/modules/modules_modCreate.html
{% extends "base.html" %}
{% block title %}Create Module{% endblock title %} 
{% block main %} 
    {% if request.user.profile.authorized %} 
        <head>
            <h1>Module Maker</h1>
        </head>
        <body>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form }}
            </form>
        </body>
    {% endif %}
{% endblock main %} 

bitwiseapp/templates/modules/modules_modUpdate.html
{% extends "base.html" %}
{% block title %}Update Module{% endblock title %} 
{% block styles %}
    <style>
        textarea {
        display: block;
        width: 100%;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
                box-sizing: border-box;
    }
    </style>
{% endblock styles %}
{% block main %} 
    {% if request.user.profile.authorized %} 
        <head>
            <h1>Module Editor</h1>
        </head>
        <body>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row my-3 mx-2">
                    <div class="col-md-8 border rounded" style="background-color: #D59D46;">
                        <div class="row my-4">
                            <div class="container border rounded" style="background-color: #EFD4B7; width: 95%;">
                                <div class="row text-center">
                                    <div class="col my-2 d-flex align-items-center">
                                        {{ form.title.errors }}
                                        <h2 class="mx-2">{{ form.title.label_tag }}</h2>
                                        {{ form.title }}
                                    </div>
                                    <div class="col my-2 d-flex align-items-center">
                                        {{ form.category.errors }}
                                        <h2 class="mx-2">{{ form.category.label_tag }}</h2>
                                        {{ form.category }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row my-4">
                            <div class="container border rounded py-3" style="background-color: #EFD4B7; width: 95%;">
                                {{ form.entry.errors }}
                                <h2>{{ form.entry.label_tag }}</h2>
                                <div class="mb-3">
                                    {{ form.entry }}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="container text-center">
                            <input type="submit" value="Publish Module" class="btn" style="background-color: #9AD86E; width: 200px;">
                            <a href="{% url 'modules:ModuleDelete'  pk=object.pk %}" class="btn" style="background-color: #eb4646; width: 200px;">Delete Module</a>
                        </div>
                    </div>
                </div>
            </form>
        </body>
    {% endif %}
{% endblock main %} 

bitwiseapp/templates/modules/modules_module.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ object.title }}{% endblock %}
{% block main %}

<a class="btn btn-secondary mb-4 text-end" href="{% url 'bitwise:index' %}">Back to Home</a>
{% if request.user == object.author.user %}
    <a class="btn btn-secondary mb-4 text-end" href="{% url 'modules:ModuleUpdate' pk=object.pk %}">Update the Module</a>
{% endif %}

<div class="container">

{% if object.category.name == "C++" %}
    <img src="{% static 'img/banner_cplusplus.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% elif object.category.name == "Web Development" %}
    <img src="{% static 'img/banner_webdev.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% elif object.category.name == "Python" %}
    <img src="{% static 'img/banner_python.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% else %}
    <img src="{% static 'img/banner_python.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% endif %}

<h2 class="text-center">{{ object.title }}</h2>
<p class="text-center text-muted"><i>By {{ object.author }}</i></p>

<p class="text-center">
    Published on <strong>{{ object.createdOn }}</strong> | 
    Last edited on <strong>{{ object.updatedOn }}</strong>
    <br>
    Lesson on: <strong>{{ object.category }}</strong>
</p>

<hr>

<p class="mt-4 mb-5">{{ object.entry|linebreaks }}</p>

<!-- GALLERY PHOTOS -->

<div class="row">
    <h2>GALLERY</h2>

    {% if request.user == object.author.user %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ gallery_form.as_div }}
        <button class="mt-2 btn btn-secondary">Submit</button>
    </form>
    {% endif %}
    {% for photo in images %}
        {% if photo.module == object %}
        <div class="col-md-4">
            <div class="card my-4 mx-auto">
            <img src="{{ photo.image.url }}" style="max-height: 250px;">
            {% if request.user == object.author.user %}
                <a href="{% url 'modules:GalleryDelete' pk=photo.pk %}" class="btn" style="background-color: #eb4646;">Delete Image</a>
            {% endif %}
        {% endif %}
            </div>
        </div>
    {% endfor %}
</div>

<br>

<!-- MORE ON THE TOPIC SECTION -->
<h3>More related modules:</h3>
<div class="card-group">
{% for module in allModules %}
    {% if module.category == object.category %}
    {% if module.pk != object.pk %}
        <div class="card">
            {% if module.category.name == "C++" %}
                <img src="{% static 'img/banner_cplusplus.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
            {% elif module.category.name == "Web Development" %}
                <img src="{% static 'img/banner_webdev.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
            {% elif module.category.name == "Python" %}
                <img src="{% static 'img/banner_python.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
            {% else %}
                <img src="https://picsum.photos/1000/250" style="width: 100%; max-height: 250px;" class="mb-4">
            {% endif %}
            <div class="card-body">
                <div class="card-title">
                    <h3>
                        <a href="{{ module.get_absolute_url }}">{{ module.title }}</a>
                        <p>From: {{ module.author }}</p>
                    </h3>
                </div>
            </div>
        </div>
    {% endif %}
    {% endif %}
{% endfor %}
</div>

<hr>

<!-- COMMENTS SECTION -->
<h5>Comments</h5>

{% if request.user.is_authenticated %}
<div class="container bg-light">
    <form method="POST" class="py-3">
        {% csrf_token %}
        {{ comment_form.entry.errors }}
        {{ comment_form.entry}}
        <button class="mt-2 btn btn-secondary">Submit</button>
    </form>
</div>
{% endif %}

<ul class="list-group list-group-flush mt-4">
{% for comment in comments %}
    <li class="list-group-item">
        {% if comment.module == object %}
            <p class="mb-0"><strong>{{ comment.author }}</strong></p>
            <small class="text-secondary">Commented at {{ comment.createdOn }} | Edited at {{ comment.updatedOn }}</small>
            {% if request.user == comment.author.user or object.author.user %}
            <br>
                <a href="{% url 'modules:CommentDelete' pk=comment.pk %}" class="btn" style="background-color: #eb4646;">Delete</a>
            {% endif %}
            <p>{{ comment.entry|linebreaks }}</p>
        {% endif %} 
    </li>
{% endfor %}
</ul>

{% if not request.user.is_authenticated %}

    <form method="POST" action="{% url 'login' %}">
        {% csrf_token %}
        <button type="submit">LOG IN</button>
    </form>

{% endif %}
</div>
{% endblock %}

bitwiseapp/templates/modules/modules_python.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bitwise | Python Editor{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.css">
    <style>
        #codearea,
        *, *:after, *:before {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        section {
            position: relative;
            padding: 2.5rem 0;
        }

        .container {
            position: relative;
            margin: 2.5% 0% 0% 0%;
            padding: 0 20px;
            width: 100%;
            max-width: 970px;
        }

        section:after, .container:after, .row:after {
            display: table;
            content: '';
            clear: both;
        }

        .code-container {
            position: relative;
            margin-bottom: 1.5rem;
            overflow: hidden;
            border-radius: 3px;
            box-shadow: 3px 3px 6px rgba(0, 0, 0, .3);
        }

        .code-container:last-child {
            margin-bottom: 0;
        }

        textarea {
            width: 100%; 
        }
    </style>
{% endblock %}
{% block main %}
    <h1>Python Code Editor</h1>
    <hr>

    <div class="container mx-auto">
        <form action="/modules/compiler/python/run" method="post">
            {% csrf_token %}
            <div class="code-container">
                <textarea id="codearea" name="codearea" rows="10" >{{ code }}</textarea>
            </div>
            <hr>
            <div>
                <h3><label for="output">Output</label></h3>
                <br>
                <textarea id="output" name="output" width="100%" height="500px" rows="10" disabled style="border: 5px solid gray">{{ output }}</textarea>
            </div>
            <br>
            <button type="submit" class="mt-2 btn btn-secondary">Run Code</button>
        </form>
    </div>

{% endblock  %}
{% block scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/codemirror.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/6.65.7/mode/python/python.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>
        // $(document).ready(function () {
        //     var url = window.location;
        //     $('ul.nav a').filter(function() {
        //         return this.href != url;
        //     }).removeClass('active');

        //     $('ul.nav a').filter(function() {
        //         return this.href == url;
        //     }).addClass('active');
        // });
        
        var codeEditor = CodeMirror.fromTextArea(document.getElementById("codearea"), {
            mode: "python",
            lineNumbers: true,
            indentUnit: 4,
            extraKeys: { Tab: "indentMore", "Shift-Tab": "indentLess" },
        });
    </script>
{% endblock %}

bitwiseapp/templates/modules/modules_search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bitwise | Search {% endblock %}
{% block main %}
    <center>
        {% if searching %}
            <h1> You Searched For... {{ searching }}!</h1>
            <br/>
            {% for module in searched %}
                <div class="card my-4 mx-auto" style="max-width: 1200px;">
                    <div class="row g-0">
                        <div class="col-md-4">
                            {% if module.category.name == 'C++' %}
                                <img src="{% static 'img/card_cplusplus.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                            {% elif module.category.name == "Web Development" %}
                                <img src="{% static 'img/card_webdev.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                            {% elif module.category.name == "Python" %}
                                <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                            {% else %}
                                <img src="{% static 'img/card_python.png' %}" class="img-fluid rounded-start" alt="placeholder" style="width: 100%; max-height: 300px;">
                            {% endif %}
                        </div>
                        <div class="col-md-8 d-flex" style="background-color: #D9D9D9;">
                            <div class="card-body align-self-center mx-4">
                                <h2 class="card-title"><a href="{{ module.get_absolute_url }}">{{ module.title }}</a></h2>
                                <p class="card-subtitle mb-2 text-muted">By {{ module.author }}</p>
                                <h5>Category: {{ module.category }}</h5>
                                <!-- <div class="card-body">
                                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe explicabo a suscipit impedit maiores dolorum similique nesciunt mollitia, omnis quaerat sed delectus quos aut id repudiandae magnam error! Odio nisi natus repellat nulla a fugiat aperiam quam dolores necessitatibus distinctio quaerat labore aut, qui odit eum eveniet nihil quis quasi.</p>
                                </div>  -->
                            </div>
                        </div>
                    </div>
                </div>  
            {% endfor %}
        {% else %}
            <h1>Waiting For Something To Happen?</h1>
        {% endif %}

    </center>
{% endblock %}