bitwiseapp/bitwise/urls.py
from django.urls import path

from .views import HomepageView

urlpatterns = [
    path("", HomepageView, name="index"),
]

app_name = "bitwise"

bitwiseapp/bitwiseapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("bitwise.urls", namespace="default")),
    path("home/", include("bitwise.urls", namespace="bitwise")),
    path("profile/", include("accounts.urls", namespace="profile")),
    path("modules/", include("modules.urls", namespace="modules")),
    path("registration/", include("django.contrib.auth.urls")),
    path("quizzes/", include("quizzes.urls", namespace="quizzes")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitwiseapp/quizzes/urls.py
from django.urls import path

from .views import (
    QuizListView,
    QuizAnswerView,
    QuizInfoDetailView,
    quiz_detail_data_view,
    save_quiz_view,
    create_quiz,
    quiz_detail,
    quiz_update,
    answer_delete,
    question_delete
)

urlpatterns = [
    path('', QuizListView.as_view(), name='quiz_list_view'),
    path('quiz/<pk>/info', QuizInfoDetailView.as_view(), name='quiz_view'),
    path('quiz/<pk>', QuizAnswerView.as_view(), name="quiz_answer"), # for answering the quiz
    path('quiz/<pk>/data', quiz_detail_data_view, name='quiz_data_view'), # for checking data before implementation for quiz
    path('quiz/<pk>/save', save_quiz_view, name='quiz_save_view'),
    path('create', create_quiz, name="create_quiz_view"),
    path('quiz/<quiz_id>/update', quiz_update, name='quiz_update'),
    path('quiz/<answer_id>/answer_delete', answer_delete, name='answer_delete'),
    path('quiz/<question_id>/question_delete', question_delete, name='question_delete')
]

app_name = 'quizzes'

bitwiseapp/quizzes/models.py
from django.db import models
from django.urls import reverse

from accounts.models import Profile

# Create your models here.

DIFFICULTY_CHOICES = (
    ("Easy", "Easy"),
    ("Medium", "Medium"),
    ("Hard", "Hard"),
)


class Topic(models.Model):
    name = models.CharField(max_length=60)
    description = models.TextField(default="Programming", blank=True, null=True)

    def __str__(self):
        return self.name


class Quiz(models.Model):
    name = models.CharField(max_length=60)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name="quiz")
    number_of_questions = models.IntegerField()
    time = models.IntegerField(help_text="duration of the quiz in minutes")
    image = models.ImageField(null=True, blank=True)
    created_by = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="quiz"
    )
    created_time = models.DateTimeField(auto_now_add=True, null=True)
    difficulty = models.CharField(
        help_text="The difficulty of the quiz", max_length=6, choices=DIFFICULTY_CHOICES
    )

    def __str__(self):
        return f"{self.name} - {self.topic}"

    def get_absolute_url(self):
        return reverse("quizzes:quiz_view", args=[self.pk])

    @property
    def get_questions(self):
        return self.questions.all()

    class Meta:
        verbose_name_plural = "Quizzes"


class Question(models.Model):
    text = models.CharField(max_length=120)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    created_time = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return f"{self.pk} - {str(self.text)[:10]}"

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"

    @property
    def get_answers(self):
        return self.answers.all()


class Answer(models.Model):
    text = models.CharField(max_length=120)
    correct = models.BooleanField(default=False)
    question = models.ForeignKey(
        Question, on_delete=models.CASCADE, related_name="answers"
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"question: {str(self.question.text)[:15]}, answer: {str(self.text)[:10]}, correct: {self.correct}"


class Result(models.Model):
    date = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)

    user = models.ForeignKey(Profile, on_delete=models.CASCADE)

    score = models.DecimalField(max_digits=5, decimal_places=2, default=0)

    def __str__(self):
        return str(self.pk)

bitwiseapp/quizzes/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from django.forms import formset_factory, modelformset_factory
from .models import Quiz, Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text', 'image',]
        widgets = {
            'text': forms.Textarea(attrs={'rows': 2, 'class': 'form-control'}),
        }
        labels = {
            'text': 'Question Text',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['text', 'correct']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 1, 'class': 'form-control'}),
        }
        labels = {
            'text': 'Answer Text',
            'correct': 'Is this the correct answer?',
        }
        def __init__(self, *args, **kwargs): # added __init__
            super().__init__(*args, **kwargs)
            self.fields['text'].widget.attrs.update({'class': 'form-control'})
            self.fields['correct'].widget.attrs.update({'class': 'form-check-input'}) # added is_correct
            

class QuizForm(forms.ModelForm):
    class Meta:
        model = Quiz
        fields = ["name", "topic", "number_of_questions", "image", "difficulty", "time" ]
    
def get_question_formset(extra=1, can_delete=True):
    return modelformset_factory(Question, form=QuestionForm, extra=extra, can_delete=can_delete)

AnswerFormSet = formset_factory(AnswerForm, extra=4, can_delete=True)

bitwiseapp/quizzes/views.py
from django.views.generic import ListView, DetailView
from django.http import JsonResponse, HttpResponseRedirect
from .models import Quiz, Result, Question, Answer
from .forms import QuizForm, QuestionForm, AnswerFormSet, get_question_formset
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse 
from django.views.generic.detail import SingleObjectMixin
from django.contrib import messages
from accounts.models import Profile
from django.db import transaction
from django.core import serializers
import logging


# Get an instance of a logger
logger = logging.getLogger(__name__)

# Quiz List view
class QuizListView(ListView):
    model = Quiz
    template_name = 'quizzes/quiz_list.html'

class QuizInfoDetailView(DetailView):
    model = Quiz
    template_name = 'quizzes/quiz_info.html'

class QuizAnswerView(DetailView):
    model = Quiz
    template_name = 'quizzes/detail.html'
    
def create_quiz(request):
    quiz_form = QuizForm()

    if request.method == 'POST':
        quiz_form = QuizForm(request.POST, request.FILES)
        if quiz_form.is_valid():
            quiz = Quiz()
            quiz.created_by = Profile.objects.get(user=request.user)
            quiz.topic = quiz_form.cleaned_data.get("topic")
            quiz.name = quiz_form.cleaned_data.get("name")
            quiz.number_of_questions = quiz_form.cleaned_data.get("number_of_questions")
            quiz.time = quiz_form.cleaned_data.get("time")
            quiz.difficulty = quiz_form.cleaned_data.get("difficulty")
            quiz.save()
            
            return redirect('quizzes:quiz_view', pk=quiz.pk)
        
    return render(request, 'quizzes/create_quiz.html', {'quiz_form': quiz_form})

# for deleting answer
def answer_delete(request, answer_id):
    answer = Answer.objects.get(pk=answer_id)
    answer.delete()
    return redirect('quizzes:quiz_update')

# for deleting question
def question_delete(request, question_id):
    question = Question.objects.get(pk=question_id)
    question.delete()
    return redirect('quizzes:quiz_update')

# for updating questions and answers
def quiz_update(request, quiz_id, *args, **kwargs):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    existing_question_count = quiz.questions.count()
    remaining_slots = max(0, quiz.number_of_questions - existing_question_count)
    
    QuestionFormSet = get_question_formset(extra=remaining_slots, can_delete=True)

    if request.method == 'POST':
        question_formset = QuestionFormSet(request.POST)
        answer_formset = AnswerFormSet(request.POST)

        if question_formset.is_valid() and answer_formset.is_valid():
            saved_questions = []
            with transaction.atomic():
                # 1. Save existing questions first
                for question_form in question_formset:
                    if question_form.cleaned_data and question_form.instance and not question_form.cleaned_data.get('DELETE', False):
                        question = question_form.save()  # Save the existing question
                        saved_questions.append(question.instance)  # add to saved list

                # 2. Handle new questions
                for question_form in question_formset:
                    if question_form.cleaned_data and not question_form.instance and not question_form.cleaned_data.get('DELETE', False):
                        if question_form.cleaned_data and not question_form.instance and not question_form.cleaned_data.get('DELETE', False):
                            instance = question_form.save(commit=False)
                            logger.debug(f"Quiz ID: {quiz.id}")  # Debug: Check quiz ID
                            instance.quiz = quiz
                            logger.debug(f"New Question Quiz ID: {instance.quiz_id}") # Debug: Check new_question.quiz_id
                            instance.save()  # Save the new question to get an ID
                            logger.debug(f"New Question ID: {instance.id}")  # Debug: Check new question ID after saving
                            saved_questions.append(instance)  # add to saved list
                            question = instance # added

                    # 3.  Save answers for each question.
                    for answer_form in answer_formset:
                        if answer_form.cleaned_data and not answer_form.cleaned_data.get('DELETE', False):
                            answer = answer_form.save(commit=False)
                            answer.question = question
                            answer.save()

            # Handle deleted questions
            for deleted_question_form in question_formset.deleted_forms:
                if deleted_question_form.cleaned_data and deleted_question_form.instance:
                    deleted_question_form.instance.delete()
            return redirect('quizzes/quiz_info.html', pk=quiz_id)

        else:
            context = {
                'quiz': quiz,
                'question_formset': question_formset,
                'answer_formset': answer_formset,
                'max_questions': quiz.number_of_questions,
            }
            return render(request, 'quizzes/quiz_update.html', context)
    else:
        initial_question_data = quiz.questions.all()
        QuestionFormSet = get_question_formset(extra=remaining_slots, can_delete=True)
        question_formset = QuestionFormSet(queryset=initial_question_data)        
        answer_formset = AnswerFormSet()
        context = {
            'quiz': quiz,
            'question_formset': question_formset,
            'answer_formset': answer_formset,
            'max_questions': quiz.number_of_questions,
        }
        return render(request, 'quizzes/quiz_update.html', context)
    
def quiz_detail(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = Question.objects.filter(quiz=quiz)
    context = {
        'quiz': quiz,
        'questions': questions,
    }
    return render(request, 'quizzes/detail.html', context)


# gets the detail of quiz in JSON (for checking purposes)
def quiz_detail_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []
    for question in quiz.get_questions:
        answers = []
        for answer in question.get_answers:
            answers.append(answer.text)
        questions.append({question.text: answers})
    
    return JsonResponse({
        'data': questions,
        'time': quiz.time
    })

# saves the responses
def save_quiz_view(request, pk):
    if request.accepts("application/json"):
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')

        questions = []

        for k in data_.keys():
            question = Question.objects.get(text=k)
            questions.append(question)

        user = request.user
        profile = get_object_or_404(Profile, user=user)
        quiz = Quiz.objects.get(pk=pk)

        score = 0
        multiplier = 100 / len(questions) 
        results = []

        for q in questions:
            a_selected = data[q.text]

            if a_selected != '':
                correct_answer = Answer.objects.filter(question=q).get(correct=True)
                if a_selected == correct_answer.text:
                    score += 1
                
                results.append({q.text: {
                    'correct_answer': correct_answer.text,
                    'answered': a_selected
                }})
            else:
                results.append({q.text: 'not answered'})

        final_score = score * multiplier


        Result.objects.create(quiz=quiz, user=profile, score=final_score)

        json_response = {
            'score': final_score,
            'correct_questions': score,
            'results': results
        }   

        return JsonResponse(json_response)
    


""" class QuizCreateView(CreateView): 
     model = Quiz 
     fields = ['name', 'topic', 'number_of_questions', 'time', 'image', 'difficulty']
     template_name = "quizzes/create_quiz.html"
     def get_success_url(self): 
         return reverse('quiz_list_view') """
     
""" class QuizCreateUpdate(SingleObjectMixin, FormView):
    model = Quiz
    template_name = "quizzes/quiz_update.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Quiz.objects.all())
        return super().get(request, *args, **kwargs)
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Quiz.objects.all())
        return super().post(self, request, *args, **kwargs)
    
    def get_form(self, form_class=None):
        return BaseQuestionFormset(
            **self.get_form_kwargs(), instance=self.object
        )
    
    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.SUCCESS, "Changes were saved.")
        return HttpResponseRedirect(self.get_success_url())
    
    def get_success_url(self):
        return reverse('quizzes:quiz_detail', kwargs={"pk": self.object.pk})

 """
# tried using this reference: https://swapps.com/blog/working-with-nested-forms-with-django/

bitwiseapp/templates/quizzes/create_quiz.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}


{% endblock scripts %}

{% block title %}Create Quiz{% endblock title %}


{% block main %}

<div class="container text-center py-4">
    <h1 class="">Create Quiz</h1>
</div>

<form method="post">
    {% csrf_token %}
    {{ quiz_form.as_p }}
    <button type="submit">Create Quiz</button>
</form>


<div class="py-3">
    <a href="{% url 'quizzes:quiz_list_view' %}" class="btn btn-danger" id="">
        Go back
    </a>
</div>


{% endblock main %}

bitwiseapp/templates/quizzes/detail.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
<script src="{% static 'js/quiz.js' %}"></script>

{% endblock scripts %}

{% block title %}{{object.name}}[Quiz] {% endblock title %}


{% block main %}


<div class="container text-center py-4">
    <h1 class="">Quiz: {{object.name}}</h1>
</div>

<div class="py-3">
    <a href="{% url 'quizzes:quiz_list_view' %}" class="btn btn-danger" id="">
        Go back
    </a>
</div>

<div class="row">
    <div class="col">
        <div class="text-secondary my-auto" id="score-box">
            <p>Total Question: {{ object.number_of_questions }}  %</p>
        </div>
    </div>
    <div class="col text-end" id="timer-box">
    </div>
</div>

<form class="mt-3" id="quiz-form">
    {% csrf_token %}
    <div id="quiz-box" class="">
    </div>
    <div class="text-center py-3">
        <button type="submit" class="mt-4 btn btn-primary btn-lg">Send</button>
    </div>
</form>

<div id="result-box">

</div>

{% endblock main %}

bitwiseapp/templates/quizzes/quiz_info.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}


{% endblock scripts %}

{% block title %}Quiz: {{ object.name }} {% endblock title %}

{% block main %}

<div class="container text-center py-4">
    <h1 class="">Quiz Info</h1>
</div>


<div class="container">
    {% if object.category.name == "C++" %}
    <img src="{% static 'img/banner_cplusplus.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% elif object.category.name == "Web Development" %}
    <img src="{% static 'img/banner_webdev.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% elif object.category.name == "Python" %}
    <img src="{% static 'img/banner_python.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% else %}
    <img src="{% static 'img/banner_python.png' %}" style="width: 100%; max-height: 250px;" class="mb-4">
{% endif %}
</div>

<h2 class="text=center">
    {{ object.title }}
</h2>
<img src="{{ photo.image.url }}" style="max-height: 250px;">
<p class="text-left">
    Topic: {{ object.topic }}
    <br>
    Time to answer: {{ object.time }}
</p>

{% if request.user == object.created_by.user %}
<div class="py-3">
    <a href="{% url 'quizzes:quiz_update' quiz_id=object.pk %}" class="btn btn-danger" id="">
        Update Quiz/Add Questions
    </a>
</div>
{% endif %}

<div class="py-3">
    <a href="{% url 'quizzes:quiz_answer' pk=object.pk %}" class="btn btn-danger" id="">
        Take Quiz
    </a>
</div>

<div class="py-3">
    <a href="{% url 'quizzes:quiz_list_view' %}" class="btn btn-danger" id="">
        Go back
    </a>
</div>


{% endblock main %}

bitwiseapp/templates/quizzes/quiz_list.html
{% extends 'base.html' %}
{% load static %}


{% block scripts %}

<script src="{% static 'js/quizzes.js' %}" defer></script>

{% endblock scripts %}


{% block title %}Home{% endblock title %}

{% block main %}


<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Start Quiz</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body-confirm">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="start-button">Start</button>
            </div>
        </div>
    </div>
</div>

<div class="">
    <h1 class="h1">
        Quiz List
    </h1>
</div>

<hr>

{% if request.user.is_authenticated %}
    <a class="btn btn-secondary mt-4 text-end" href="{% url 'quizzes:create_quiz_view' %}">Create Quiz</a>
{% endif %}
<div class="row">
    {% for object in object_list %}
    <div class="col-md-4"> 
        <div class="card my-4 mx-auto">
            <div class="row g-0">
                <div class="d-flex" style="background-color: #D9D9D9;">
                    <div class="card-body align-self-center mx-4">
                        <h2 class="card-title"><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></h2>
                        <p class="card-subtitle mb-2 text-muted">By {{ object.created_by }}</p>
                        <h5>Category: {{ object.topic.name }}</h5>
                        <h5>Difficulty: {{ object.difficulty }}</h5>
                        <!-- <div class="card-body">
                            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Saepe explicabo a suscipit impedit maiores dolorum similique nesciunt mollitia, omnis quaerat sed delectus quos aut id repudiandae magnam error! Odio nisi natus repellat nulla a fugiat aperiam quam dolores necessitatibus distinctio quaerat labore aut, qui odit eum eveniet nihil quis quasi.</p>
                        </div>  -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <button type="button" class="btn btn-link modal-button bg-secondary" data-pk="{{object.pk}}" data-date="{{object.date}}"
        data-name="{{object.name}}" data-description="{{object.description}}" data-topic="{{object.topic.name}}"
        data-questions="{{object.number_of_questions}}" data-difficulty="{{object.difficulty}}"
        data-time="{{object.time}}" data-bs-toggle="modal"
        data-bs-target="#quizStartModal" data-created="{{object.created_time}}">
        {{object.name}}
    </button> -->
    {% endfor %}
</div>

{% endblock main %}

bitwiseapp/templates/quizzes/quiz_update.html
{% extends 'base.html' %}
{% load static %}

{% block scripts %}

<script>
  document.addEventListener('DOMContentLoaded', function() {
      const deleteQuestionButtons = document.querySelectorAll('.delete-question-btn');

      deleteQuestionButtons.forEach(button => {
          button.addEventListener('click', function() {
              const formPrefix = this.dataset.formPrefix;
              const deleteCheckbox = document.querySelector(`#id_${formPrefix}-DELETE`);
              const questionFormDiv = this.closest('.question-form');

              if (deleteCheckbox && questionFormDiv) {
                  deleteCheckbox.checked = true;
                  questionFormDiv.style.display = 'none';
              }
          });
      });
  });
</script>

{% endblock scripts %}

{% block title %}Update Quiz{% endblock title %}

{% block main %}
  <h1>Update Quiz: {{ quiz.title }}</h1>

  <form method="post">
    {% csrf_token %}

    <h2>Questions</h2>
        {{ question_formset.management_form }}
        {% for question_form in question_formset %}
        <h2>Question {{ forloop.counter }}</h2>
        <div class="question-form">
          {{ question_form.as_p }}
          {{ question_form.id }}  {# Important for identifying existing questions for deletion #}
          <button type="button" class="delete-question-btn" data-form-prefix="{{ question_form.prefix }}">Delete Question</button>

          <h3>Answers for Question {{ forloop.counter }}</h3>
          {% if question_form.instance.pk %}  {# Check if the question instance has a primary key #}
              {% for answer in question_form.instance.answers.all %}
                  <div class="answer-form">
                      <p>Answer Text: {{ answer.text }}</p>
                      <p>Is Correct: {{ answer.correct }}</p>
                  </div>
              {% endfor %}
          {% endif %}
          {{ answer_formset.management_form }}
          {% for answer_form in answer_formset %}
              <div class="answer-form">
                  {{ answer_form.as_p }}
              </div>
          {% endfor %}
        </div>
        {% endfor %}

    <button type="submit">Update Quiz</button>
  </form>

  <a href="{% url 'quizzes:quiz_view' pk=quiz.pk %}">Back to Quiz Detail</a>

<div class="py-3">
    <a href="{% url 'quizzes:quiz_list_view' %}" class="btn btn-danger" id="">
        Go back
    </a>
</div>
{% endblock main %}